spring.application.name=back-end

spring.datasource.url=jdbc:mysql://<mysql_host>/cms?usessl=false
spring.datasource.username=root

spring.datasource.password=<mysql_password>
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:<mongodb_password>@<mongodb_host>:27017/prescriptions?authSource=admin"

management.endpoint.health.show-details=always
management.health.db.enabled=true


api.path=/
jwt.secret=$!@#$^%$$$%####$DDCPN0234FCFDPD8670M


# This setting tells Spring Boot where to look for static assets (e.g., CSS, JS, images).
spring.web.resources.static-locations=classpath:/static/

# -------------------------
# Thymeleaf Configuration
# -------------------------
# Defines the base directory for Thymeleaf templates.
spring.thymeleaf.prefix=classpath:/templates/
# Specifies that all Thymeleaf templates will have an .html suffix.
spring.thymeleaf.suffix=.html
# Sets the rendering mode for templates. HTML mode is most commonly used for rendering well-formed HTML5 pages.
spring.thymeleaf.mode=HTML
# Disables caching of templates.
# Useful during development to see changes immediately without restarting the app.
spring.thymeleaf.cache=false   
# Ensures that all templates are read using UTF-8 encoding to support internationalization and special characters. 
spring.thymeleaf.encoding=UTF-8